GET http://localhost:3000/user-access
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY5MDMzNjM3NywiZXhwIjoxNjkwMzM2MzkyfQ.dJwM9sn5gLpbe-Qf2sTapQEkglsAb-aFcwTXlG5_HxE

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": 
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY5MDMzNjMzMn0.bJ7IUF-l3k3i6JNdKIgURz513i3hYjnXWeWVvivymn4"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": 
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY5MDMzNjMzMn0.bJ7IUF-l3k3i6JNdKIgURz513i3hYjnXWeWVvivymn4"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Kyle"
}
